apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: $(profile-name-2)
spec:
  owner:
    kind: User
    name: $(user-2)

---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: $(profile-name-2-other-ns)
spec:
  owner:
    kind: User
    name: $(user-2)

  # resourceQuotaSpec:    # resource quota can be set optionally
  #   hard:
  #     cpu: "2"
  #     memory: 2Gi
  #     requests.nvidia.com/gpu: "1"
  #     persistentvolumeclaims: "1"
  #     requests.storage: "5Gi"
