---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-token
  namespace: cert-manager
stringData:
  CF_API_TOKEN: REPLACE-ME

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: akash@flaskd.in
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - selector:
        dnsZones:
          - "flaskd.work"
          - "*.flaskd.work"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name:  api-token
            key: CF_API_TOKEN