---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: Always
        name: test-nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test-nginx-11.flaskd.work
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test-nginx